[build]
builder = "nixpacks"
buildCommand = "cd TravelSathi && mvn clean package -DskipTests"

[deploy]
startCommand = "cd TravelSathi && java -Dserver.port=$PORT -jar target/*.jar"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
